namespace: ecomm

app: backend

replicacount: 1

image:
  repository: hello-world
  tag: ""
  restartPolicy: Always

imagePullSecrets: 
   name: deploy

service:
  name: backend-svc
  type: NodePort
  port: 3000  
  targetPort: 3000
  nodePort: 32000
  protocol: TCP

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80