apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: e-commerce
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      restartPolicy: Always
      containers:
        - name: backend
          image: linuxappvm.eastus.cloudapp.azure.com:5050/root/e-comm-app/backend:169
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
      imagePullSecrets:
        - name: deploy