apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: e-commerce
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  template:
    spec:
      restartPolicy: Always
      containers:
        - name: backend
          image: linuxappvm.eastus.cloudapp.azure.com:5050/root/e-comm-app/backend:imagetag
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      imagePullSecrets:
        - name: deploy