apiVersion: v1
kind: Service
metadata:
  namespace: e-commerce
  name: backend-svc
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: backend-svc
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort