apiVersion: v1
kind: Service
metadata:
  namespace: e-commerce
  name: e-commerceservice-backend
  labels:
    app: e-comm
spec:
  selector:
    app: e-comm
  ports:
    - name: e-commerceservice-backend
      protocol: TCP
      port: 80
      targetPort: 3002
  type: NodePort

