apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: e-commerce
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      restartPolicy: Always
      containers:
        - name: frontend
          image: linuxappvm.eastus.cloudapp.azure.com:5050/root/e-comm-app/frontend:165
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      imagePullSecrets:
        - name: my-secret