apiVersion: v1
kind: Service
metadata:
  namespace: e-commerce
  name: frontend-svc
spec:
  selector:
    app: frontend
  ports:
    - name: frontend-svc
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort