apiVersion: v1
kind: Service
metadata:
  namespace: e-commerce
  name: frontend-svc
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: frontend-svc
      protocol: TCP
      port: 30000  # Fixed port for NodePort service
      targetPort: 80
  type: NodePort