apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJsaW51eGFwcHZtLmVhc3R1cy5jbG91ZGFwcC5henVyZS5jb206NTA1MCI6eyJ1c2VybmFtZSI6InJvb3QiLCJwYXNzd29yZCI6ImdscGF0LXVZUDd0N0NfZ29ESDd5aUt4YTI0IiwiYXV0aCI6ImNtOXZkRHBuYkhCaGRDMTFXVkEzZERkRFgyZHZSRWczZVdsTGVHRXlOQT09In19fQ==
kind: Secret
metadata:
  name:  {{ .Values.imagePullSecrets.name }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
