namespace: ecomm

app: frontend

replicacount: 1

image:
  repository: nginx
  tag: ""
  restartPolicy: Always

imagePullSecrets: 
   name: my-secret

service:
  name: frontend-svc
  type: NodePort
  port: 30000  
  targetPort: 80
  nodePort: 32003
  protocol: TCP

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80